name: Collect videos and update spreadsheet

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # @v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # @v6.1.0
        with:
          node-version: "25.2.1"

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # @v4.2.0
        with:
          version: 10

      - name: Install dependencies
        run: |
          pnpm i
          cd collector
          pnpm i

      - name: Setup Google credentials
        working-directory: collector
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json

      - name: Run daily collect
        working-directory: collector
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: pnpm start
